USE [master]
GO

/****** Object:  Database [syslog]    Script Date: 8/15/2022 5:36:45 PM ******/
CREATE DATABASE [syslog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'syslog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\syslog.mdf' , SIZE = 5185536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'syslog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\syslog_log.ldf' , SIZE = 13049856KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [syslog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [syslog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [syslog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [syslog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [syslog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [syslog] SET ARITHABORT OFF 
GO

ALTER DATABASE [syslog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [syslog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [syslog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [syslog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [syslog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [syslog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [syslog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [syslog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [syslog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [syslog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [syslog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [syslog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [syslog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [syslog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [syslog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [syslog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [syslog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [syslog] SET RECOVERY FULL 
GO

ALTER DATABASE [syslog] SET  MULTI_USER 
GO

ALTER DATABASE [syslog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [syslog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [syslog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [syslog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [syslog] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [syslog] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [syslog] SET QUERY_STORE = OFF
GO

ALTER DATABASE [syslog] SET  READ_WRITE 
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[res_logs](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[devip] [nvarchar](50) NULL,
	[devid] [nvarchar](50) NULL,
	[datetime] [nvarchar](50) NULL,
	[opt] [nvarchar](100) NULL,
	[msg] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[sec_logs](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[datetime] [nvarchar](25) NOT NULL,
	[devname] [nvarchar](30) NOT NULL,
	[type] [nvarchar](100) NOT NULL,
	[loguser] [nvarchar](50) NOT NULL,
	[msg] [nvarchar](max) NULL,
	[ui] [nvarchar](30) NOT NULL,
	[attack] [nvarchar](max) NULL,
	[logall] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[usergroup](
	[user] [nvarchar](50) NOT NULL,
	[group] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_usergroup] PRIMARY KEY CLUSTERED 
(
	[user] ASC,
	[group] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO